name: Command Testing

on:
  issue_comment:
    types: [created]

jobs:
  lock-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'bot.lock') == true
    steps:
      - name: Lock issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'lock-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
  close-issue:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'bot.close') == true
    steps:
      - name: Close issue
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
  add-bug-label:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'bot.addl.bug') == true
    steps:
      - name: Add label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-label'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'bug'
  add-feature-label:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, 'bot.addl.feature') == true
    steps:
      - name: Add label
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'add-label'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          labels: 'enhancement'